# Config file to build blast database based on taxonomical sampling

# Base path for output
paths:
  results: "results_test"

# Set which sampling method and database to use
method:
  sample_refseq: False
  subsample_gtdb: True
  prune_gtdb: False

# Options for sampling the RefSeq-database
sample_refseq:
    max_taxa: 1
    taxonomic_level: "phylum"

# Options for sampling the GTDB-database using a set number of taxa for the selected
# taxonomical level.
subsample_gtdb:
  max_taxa: 1
  taxonomic_level: "class"
  completeness: 90
  contamination: 5
  gtdb_representative: True
  sampling_scheme: "sampling_scheme.yaml"

# Or use phylogenetic distance from the GTDB phylogeny to trim to a set
# number of taxa.
prune_gtdb:
  bac120: 1000
  ar53: 200
  completeness: 90
  contamination: 5

# All records in GenBank does not have an associated annotation.
# Setting the following option to True will download these redords
# and annotate them with Prodigal and include them in the database.
keep_non_annotated: True
