# Config file to build blast database based on taxonomical sampling

# Base path for output
paths:
  results: "results_test_subsample_gtdb"

# Set which sampling method and database to use.
# auto_download: false will give the user the possibility
# to add or remove taxa after the sampling
method:
  subsample_refseq: False
  subsample_gtdb: True
  prune_gtdb: False
  auto_download: False

# Set what software to use for building output database
output:
  blast: True
  diamond: True
  mmseqs: True


# Options for sampling the RefSeq-database
sample_refseq:
    max_taxa: 1
    taxonomic_level: "phylum"

# Options for sampling the GTDB-database using a set number of taxa for the selected
# taxonomical level.
subsample_gtdb:
  sampling_scheme: "../config/sampling_scheme.planctomycetota.yaml"
  completeness: 0
  contamination: 100
  gtdb_species_representative: False

# Or use phylogenetic distance from the GTDB phylogeny to trim to a set
# number of taxa.
prune_gtdb:
  bac120: 100
  ar53: 20
  completeness: 90
  contamination: 5
