# Config file to build blast database based on taxonomical sampling

# Base path for output
paths:
  results: "results_test_prune"

# Set which sampling method and database to use
method:
  sample_refseq: False
  subsample_gtdb: False
  prune_gtdb: True

# Options for sampling the RefSeq-database
sample_refseq:
    max_taxa: 1
    taxonomic_level: "phylum"

# Options for sampling the GTDB-database using a set number of taxa for the selected
# taxonomical level.
subsample_gtdb:
  max_taxa: 1
  taxonomic_level: "class"
  completeness: 90
  contamination: 5
  gtdb_representative: True

# Or use phylogenetic distance from the GTDB phylogeny to trim to a set
# number of taxa.
prune_gtdb:
  bac120: 100
  ar53: 20
  completeness: 90
  contamination: 5
